framework:
    notifier:
        texter_transports:
            mail: 'mailto://symfonymail022@gmail.com'  # Replace with your email address
        channel_policy:
            # Use 'mail' for all priority levels
            urgent: ['mail']
            high: ['mail']
            medium: ['mail']
            low: ['mail']
        admin_recipients:
            - { email: symfonymail022@gmail.com }  # Replace with your admin email address
