<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20240413011637 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE imageclub (idImage INT NOT NULL, idClub INT NOT NULL, INDEX IDX_AD6FF1DBD2F94742 (idImage), INDEX IDX_AD6FF1DBCB1366EC (idClub), PRIMARY KEY(idImage, idClub)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE imageevent (idImage INT NOT NULL, idEvent INT NOT NULL, INDEX IDX_94B19022D2F94742 (idImage), INDEX IDX_94B190222C6A49BA (idEvent), PRIMARY KEY(idImage, idEvent)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE likedevent (rating INT NOT NULL, idUser INT NOT NULL, idEvent INT NOT NULL, INDEX IDX_E277D42EFE6E88D7 (idUser), INDEX IDX_E277D42E2C6A49BA (idEvent), PRIMARY KEY(idUser, idEvent)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('ALTER TABLE imageclub ADD CONSTRAINT FK_AD6FF1DBD2F94742 FOREIGN KEY (idImage) REFERENCES club (id)');
        $this->addSql('ALTER TABLE imageclub ADD CONSTRAINT FK_AD6FF1DBCB1366EC FOREIGN KEY (idClub) REFERENCES image (id)');
        $this->addSql('ALTER TABLE imageevent ADD CONSTRAINT FK_94B19022D2F94742 FOREIGN KEY (idImage) REFERENCES event (id)');
        $this->addSql('ALTER TABLE imageevent ADD CONSTRAINT FK_94B190222C6A49BA FOREIGN KEY (idEvent) REFERENCES image (id)');
        $this->addSql('ALTER TABLE likedevent ADD CONSTRAINT FK_E277D42EFE6E88D7 FOREIGN KEY (idUser) REFERENCES user (id)');
        $this->addSql('ALTER TABLE likedevent ADD CONSTRAINT FK_E277D42E2C6A49BA FOREIGN KEY (idEvent) REFERENCES event (id)');
        $this->addSql('ALTER TABLE cart CHANGE idUser idUser INT DEFAULT NULL');
        $this->addSql('ALTER TABLE cart ADD CONSTRAINT FK_BA388B7FE6E88D7 FOREIGN KEY (idUser) REFERENCES user (id)');
        $this->addSql('CREATE INDEX IDX_BA388B7FE6E88D7 ON cart (idUser)');
        $this->addSql('ALTER TABLE claim CHANGE date date DATE NOT NULL, CHANGE closuredate closureDate DATE NOT NULL, CHANGE idUser idUser INT DEFAULT NULL, CHANGE idClub idClub INT DEFAULT NULL');
        $this->addSql('ALTER TABLE claim ADD CONSTRAINT FK_A769DE27FE6E88D7 FOREIGN KEY (idUser) REFERENCES user (id)');
        $this->addSql('ALTER TABLE claim ADD CONSTRAINT FK_A769DE27CB1366EC FOREIGN KEY (idClub) REFERENCES club (id)');
        $this->addSql('CREATE INDEX IDX_A769DE27FE6E88D7 ON claim (idUser)');
        $this->addSql('CREATE INDEX IDX_A769DE27CB1366EC ON claim (idClub)');
        $this->addSql('ALTER TABLE club CHANGE starttime startTime TIME NOT NULL, CHANGE endtime endTime TIME NOT NULL, CHANGE idUser idUser INT DEFAULT NULL');
        $this->addSql('ALTER TABLE club ADD CONSTRAINT FK_B8EE3872FE6E88D7 FOREIGN KEY (idUser) REFERENCES user (id)');
        $this->addSql('CREATE INDEX IDX_B8EE3872FE6E88D7 ON club (idUser)');
        $this->addSql('ALTER TABLE composed DROP FOREIGN KEY FK_6CA7B3891AD5CDBF');
        $this->addSql('ALTER TABLE composed DROP FOREIGN KEY FK_6CA7B3894584665A');
        $this->addSql('DROP INDEX IDX_6CA7B3894584665A ON composed');
        $this->addSql('DROP INDEX IDX_6CA7B3891AD5CDBF ON composed');
        $this->addSql('DROP INDEX `primary` ON composed');
        $this->addSql('ALTER TABLE composed ADD quantity INT NOT NULL, ADD size VARCHAR(255) NOT NULL, ADD idCart INT NOT NULL, ADD idProduct INT NOT NULL, DROP cart_id, DROP product_id');
        $this->addSql('ALTER TABLE composed ADD CONSTRAINT FK_6CA7B389785ED629 FOREIGN KEY (idCart) REFERENCES cart (id)');
        $this->addSql('ALTER TABLE composed ADD CONSTRAINT FK_6CA7B389C3F36F5F FOREIGN KEY (idProduct) REFERENCES product (id)');
        $this->addSql('CREATE INDEX IDX_6CA7B389785ED629 ON composed (idCart)');
        $this->addSql('CREATE INDEX IDX_6CA7B389C3F36F5F ON composed (idProduct)');
        $this->addSql('ALTER TABLE composed ADD PRIMARY KEY (idCart, idProduct)');
        $this->addSql('ALTER TABLE event DROP idImage, DROP idPlanner, CHANGE datedeb dateDeb DATE NOT NULL, CHANGE datefin dateFin DATE NOT NULL, CHANGE starttime startTime TIME NOT NULL, CHANGE endtime endTime TIME NOT NULL, CHANGE idClub idClub INT DEFAULT NULL');
        $this->addSql('ALTER TABLE event ADD CONSTRAINT FK_3BAE0AA7CB1366EC FOREIGN KEY (idClub) REFERENCES club (id)');
        $this->addSql('CREATE INDEX IDX_3BAE0AA7CB1366EC ON event (idClub)');
        $this->addSql('ALTER TABLE paymentevent DROP FOREIGN KEY FK_4708EDC84C3A3BB');
        $this->addSql('ALTER TABLE paymentevent DROP FOREIGN KEY FK_4708EDC871F7E88B');
        $this->addSql('DROP INDEX IDX_4708EDC84C3A3BB ON paymentevent');
        $this->addSql('DROP INDEX IDX_4708EDC871F7E88B ON paymentevent');
        $this->addSql('DROP INDEX `primary` ON paymentevent');
        $this->addSql('ALTER TABLE paymentevent ADD idPayment INT NOT NULL, ADD idEvent INT NOT NULL, DROP event_id, DROP payment_id');
        $this->addSql('ALTER TABLE paymentevent ADD CONSTRAINT FK_4708EDC87D91EFFF FOREIGN KEY (idPayment) REFERENCES event (id)');
        $this->addSql('ALTER TABLE paymentevent ADD CONSTRAINT FK_4708EDC82C6A49BA FOREIGN KEY (idEvent) REFERENCES payment (id)');
        $this->addSql('CREATE INDEX IDX_4708EDC87D91EFFF ON paymentevent (idPayment)');
        $this->addSql('CREATE INDEX IDX_4708EDC82C6A49BA ON paymentevent (idEvent)');
        $this->addSql('ALTER TABLE paymentevent ADD PRIMARY KEY (idPayment, idEvent)');
        $this->addSql('ALTER TABLE image DROP idProduct, DROP idClub, DROP idEvent, DROP refStadium');
        $this->addSql('ALTER TABLE notification DROP FOREIGN KEY FK_BF5476CA786A81FB');
        $this->addSql('DROP INDEX IDX_BF5476CA786A81FB ON notification');
        $this->addSql('ALTER TABLE notification CHANGE iduser_id idUser INT DEFAULT NULL');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_BF5476CAFE6E88D7 FOREIGN KEY (idUser) REFERENCES user (id)');
        $this->addSql('CREATE INDEX IDX_BF5476CAFE6E88D7 ON notification (idUser)');
        $this->addSql('ALTER TABLE `order` CHANGE date date DATE NOT NULL, CHANGE idCart idCart INT DEFAULT NULL');
        $this->addSql('ALTER TABLE `order` ADD CONSTRAINT FK_F5299398785ED629 FOREIGN KEY (idCart) REFERENCES `order` (id)');
        $this->addSql('CREATE INDEX IDX_F5299398785ED629 ON `order` (idCart)');
        $this->addSql('ALTER TABLE paymentorder DROP FOREIGN KEY FK_898F74F78D9F6D38');
        $this->addSql('ALTER TABLE paymentorder DROP FOREIGN KEY FK_898F74F74C3A3BB');
        $this->addSql('DROP INDEX IDX_898F74F78D9F6D38 ON paymentorder');
        $this->addSql('DROP INDEX IDX_898F74F74C3A3BB ON paymentorder');
        $this->addSql('DROP INDEX `primary` ON paymentorder');
        $this->addSql('ALTER TABLE paymentorder ADD idPayment INT NOT NULL, ADD idOrder INT NOT NULL, DROP order_id, DROP payment_id');
        $this->addSql('ALTER TABLE paymentorder ADD CONSTRAINT FK_898F74F77D91EFFF FOREIGN KEY (idPayment) REFERENCES `order` (id)');
        $this->addSql('ALTER TABLE paymentorder ADD CONSTRAINT FK_898F74F7E2EDD085 FOREIGN KEY (idOrder) REFERENCES payment (id)');
        $this->addSql('CREATE INDEX IDX_898F74F77D91EFFF ON paymentorder (idPayment)');
        $this->addSql('CREATE INDEX IDX_898F74F7E2EDD085 ON paymentorder (idOrder)');
        $this->addSql('ALTER TABLE paymentorder ADD PRIMARY KEY (idPayment, idOrder)');
        $this->addSql('ALTER TABLE payment DROP idEvent, DROP idOder, DROP idReservation, DROP idSubscription, CHANGE idUser idUser INT DEFAULT NULL');
        $this->addSql('ALTER TABLE payment ADD CONSTRAINT FK_6D28840DFE6E88D7 FOREIGN KEY (idUser) REFERENCES user (id)');
        $this->addSql('CREATE INDEX IDX_6D28840DFE6E88D7 ON payment (idUser)');
        $this->addSql('ALTER TABLE imageproduct DROP FOREIGN KEY FK_8564BDE63DA5256D');
        $this->addSql('ALTER TABLE imageproduct DROP FOREIGN KEY FK_8564BDE64584665A');
        $this->addSql('DROP INDEX IDX_8564BDE64584665A ON imageproduct');
        $this->addSql('DROP INDEX IDX_8564BDE63DA5256D ON imageproduct');
        $this->addSql('DROP INDEX `primary` ON imageproduct');
        $this->addSql('ALTER TABLE imageproduct ADD idImage INT NOT NULL, ADD idProduct INT NOT NULL, DROP product_id, DROP image_id');
        $this->addSql('ALTER TABLE imageproduct ADD CONSTRAINT FK_8564BDE6D2F94742 FOREIGN KEY (idImage) REFERENCES product (id)');
        $this->addSql('ALTER TABLE imageproduct ADD CONSTRAINT FK_8564BDE6C3F36F5F FOREIGN KEY (idProduct) REFERENCES image (id)');
        $this->addSql('CREATE INDEX IDX_8564BDE6D2F94742 ON imageproduct (idImage)');
        $this->addSql('CREATE INDEX IDX_8564BDE6C3F36F5F ON imageproduct (idProduct)');
        $this->addSql('ALTER TABLE imageproduct ADD PRIMARY KEY (idImage, idProduct)');
        $this->addSql('ALTER TABLE reservation DROP FOREIGN KEY FK_42C849556A2E8B35');
        $this->addSql('ALTER TABLE reservation CHANGE date date DATE NOT NULL, CHANGE starttime startTime TIME NOT NULL, CHANGE endtime endTime TIME NOT NULL, CHANGE idPlayer idPlayer INT DEFAULT NULL');
        $this->addSql('ALTER TABLE reservation ADD CONSTRAINT FK_42C84955FB08D2FF FOREIGN KEY (idPlayer) REFERENCES user (id)');
        $this->addSql('CREATE INDEX IDX_42C84955FB08D2FF ON reservation (idPlayer)');
        $this->addSql('DROP INDEX idx_42c849556a2e8b35 ON reservation');
        $this->addSql('CREATE INDEX IDX_42C84955A593B2A9 ON reservation (refStadium)');
        $this->addSql('ALTER TABLE reservation ADD CONSTRAINT FK_42C849556A2E8B35 FOREIGN KEY (refstadium) REFERENCES stadium (reference)');
        $this->addSql('ALTER TABLE paymentreservation DROP FOREIGN KEY FK_147538F84C3A3BB');
        $this->addSql('ALTER TABLE paymentreservation DROP FOREIGN KEY FK_147538F8B83297E7');
        $this->addSql('DROP INDEX IDX_147538F8B83297E7 ON paymentreservation');
        $this->addSql('DROP INDEX IDX_147538F84C3A3BB ON paymentreservation');
        $this->addSql('DROP INDEX `primary` ON paymentreservation');
        $this->addSql('ALTER TABLE paymentreservation ADD idreservation INT NOT NULL, ADD idPayment INT NOT NULL, DROP reservation_id, DROP payment_id');
        $this->addSql('ALTER TABLE paymentreservation ADD CONSTRAINT FK_147538F87D91EFFF FOREIGN KEY (idPayment) REFERENCES reservation (id)');
        $this->addSql('ALTER TABLE paymentreservation ADD CONSTRAINT FK_147538F8840939FA FOREIGN KEY (idreservation) REFERENCES payment (id)');
        $this->addSql('CREATE INDEX IDX_147538F87D91EFFF ON paymentreservation (idPayment)');
        $this->addSql('CREATE INDEX IDX_147538F8840939FA ON paymentreservation (idreservation)');
        $this->addSql('ALTER TABLE paymentreservation ADD PRIMARY KEY (idPayment, idreservation)');
        $this->addSql('ALTER TABLE stadium DROP FOREIGN KEY FK_E604044FBE1D585C');
        $this->addSql('DROP INDEX IDX_E604044FBE1D585C ON stadium');
        $this->addSql('ALTER TABLE stadium CHANGE idclub_id idClub INT DEFAULT NULL');
        $this->addSql('ALTER TABLE stadium ADD CONSTRAINT FK_E604044FCB1366EC FOREIGN KEY (idClub) REFERENCES club (id)');
        $this->addSql('CREATE INDEX IDX_E604044FCB1366EC ON stadium (idClub)');
        $this->addSql('ALTER TABLE subscription DROP FOREIGN KEY FK_A3C664D3786A81FB');
        $this->addSql('DROP INDEX IDX_A3C664D3786A81FB ON subscription');
        $this->addSql('ALTER TABLE subscription CHANGE startdate startDate DATE NOT NULL, CHANGE enddate endDate DATE NOT NULL, CHANGE idOffer idOffer INT DEFAULT NULL, CHANGE iduser_id idUser INT DEFAULT NULL');
        $this->addSql('ALTER TABLE subscription ADD CONSTRAINT FK_A3C664D33E12C423 FOREIGN KEY (idOffer) REFERENCES offer (id)');
        $this->addSql('ALTER TABLE subscription ADD CONSTRAINT FK_A3C664D3FE6E88D7 FOREIGN KEY (idUser) REFERENCES user (id)');
        $this->addSql('CREATE INDEX IDX_A3C664D33E12C423 ON subscription (idOffer)');
        $this->addSql('CREATE INDEX IDX_A3C664D3FE6E88D7 ON subscription (idUser)');
        $this->addSql('ALTER TABLE paymentsubscription DROP FOREIGN KEY FK_BF706F74C3A3BB');
        $this->addSql('ALTER TABLE paymentsubscription DROP FOREIGN KEY FK_BF706F79A1887DC');
        $this->addSql('DROP INDEX IDX_BF706F79A1887DC ON paymentsubscription');
        $this->addSql('DROP INDEX IDX_BF706F74C3A3BB ON paymentsubscription');
        $this->addSql('DROP INDEX `primary` ON paymentsubscription');
        $this->addSql('ALTER TABLE paymentsubscription ADD idPayment INT NOT NULL, ADD idSubscription INT NOT NULL, DROP subscription_id, DROP payment_id');
        $this->addSql('ALTER TABLE paymentsubscription ADD CONSTRAINT FK_BF706F77D91EFFF FOREIGN KEY (idPayment) REFERENCES subscription (id)');
        $this->addSql('ALTER TABLE paymentsubscription ADD CONSTRAINT FK_BF706F7FD58C022 FOREIGN KEY (idSubscription) REFERENCES payment (id)');
        $this->addSql('CREATE INDEX IDX_BF706F77D91EFFF ON paymentsubscription (idPayment)');
        $this->addSql('CREATE INDEX IDX_BF706F7FD58C022 ON paymentsubscription (idSubscription)');
        $this->addSql('ALTER TABLE paymentsubscription ADD PRIMARY KEY (idPayment, idSubscription)');
        $this->addSql('ALTER TABLE user ADD is_verified TINYINT(1) NOT NULL, DROP idEvent, CHANGE firstname firstName VARCHAR(20) NOT NULL, CHANGE lastname lastName VARCHAR(20) NOT NULL, CHANGE birthdate birthDate DATE NOT NULL, CHANGE email email VARCHAR(20) NOT NULL, CHANGE creationdate creationDate DATE NOT NULL');
        $this->addSql('ALTER TABLE useractivitylog DROP FOREIGN KEY FK_AC92FBF758E0A285');
        $this->addSql('DROP INDEX IDX_AC92FBF758E0A285 ON useractivitylog');
        $this->addSql('ALTER TABLE useractivitylog ADD loginTime TIME NOT NULL, DROP logintimestamp, CHANGE userid_id idUser INT DEFAULT NULL');
        $this->addSql('ALTER TABLE useractivitylog ADD CONSTRAINT FK_AC92FBF7FE6E88D7 FOREIGN KEY (idUser) REFERENCES user (id)');
        $this->addSql('CREATE INDEX IDX_AC92FBF7FE6E88D7 ON useractivitylog (idUser)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE imageclub DROP FOREIGN KEY FK_AD6FF1DBD2F94742');
        $this->addSql('ALTER TABLE imageclub DROP FOREIGN KEY FK_AD6FF1DBCB1366EC');
        $this->addSql('ALTER TABLE imageevent DROP FOREIGN KEY FK_94B19022D2F94742');
        $this->addSql('ALTER TABLE imageevent DROP FOREIGN KEY FK_94B190222C6A49BA');
        $this->addSql('ALTER TABLE likedevent DROP FOREIGN KEY FK_E277D42EFE6E88D7');
        $this->addSql('ALTER TABLE likedevent DROP FOREIGN KEY FK_E277D42E2C6A49BA');
        $this->addSql('DROP TABLE imageclub');
        $this->addSql('DROP TABLE imageevent');
        $this->addSql('DROP TABLE likedevent');
        $this->addSql('ALTER TABLE cart DROP FOREIGN KEY FK_BA388B7FE6E88D7');
        $this->addSql('DROP INDEX IDX_BA388B7FE6E88D7 ON cart');
        $this->addSql('ALTER TABLE cart CHANGE idUser idUser VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE claim DROP FOREIGN KEY FK_A769DE27FE6E88D7');
        $this->addSql('ALTER TABLE claim DROP FOREIGN KEY FK_A769DE27CB1366EC');
        $this->addSql('DROP INDEX IDX_A769DE27FE6E88D7 ON claim');
        $this->addSql('DROP INDEX IDX_A769DE27CB1366EC ON claim');
        $this->addSql('ALTER TABLE claim CHANGE date date VARCHAR(255) NOT NULL, CHANGE closureDate closuredate VARCHAR(255) NOT NULL, CHANGE idUser idUser VARCHAR(255) NOT NULL, CHANGE idClub idClub VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE club DROP FOREIGN KEY FK_B8EE3872FE6E88D7');
        $this->addSql('DROP INDEX IDX_B8EE3872FE6E88D7 ON club');
        $this->addSql('ALTER TABLE club CHANGE startTime starttime VARCHAR(255) NOT NULL, CHANGE endTime endtime VARCHAR(255) NOT NULL, CHANGE idUser idUser VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE composed DROP FOREIGN KEY FK_6CA7B389785ED629');
        $this->addSql('ALTER TABLE composed DROP FOREIGN KEY FK_6CA7B389C3F36F5F');
        $this->addSql('DROP INDEX IDX_6CA7B389785ED629 ON composed');
        $this->addSql('DROP INDEX IDX_6CA7B389C3F36F5F ON composed');
        $this->addSql('DROP INDEX `PRIMARY` ON composed');
        $this->addSql('ALTER TABLE composed ADD cart_id INT NOT NULL, ADD product_id INT NOT NULL, DROP quantity, DROP size, DROP idCart, DROP idProduct');
        $this->addSql('ALTER TABLE composed ADD CONSTRAINT FK_6CA7B3891AD5CDBF FOREIGN KEY (cart_id) REFERENCES cart (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE composed ADD CONSTRAINT FK_6CA7B3894584665A FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE CASCADE');
        $this->addSql('CREATE INDEX IDX_6CA7B3894584665A ON composed (product_id)');
        $this->addSql('CREATE INDEX IDX_6CA7B3891AD5CDBF ON composed (cart_id)');
        $this->addSql('ALTER TABLE composed ADD PRIMARY KEY (cart_id, product_id)');
        $this->addSql('ALTER TABLE event DROP FOREIGN KEY FK_3BAE0AA7CB1366EC');
        $this->addSql('DROP INDEX IDX_3BAE0AA7CB1366EC ON event');
        $this->addSql('ALTER TABLE event ADD idImage VARCHAR(255) NOT NULL, ADD idPlanner VARCHAR(255) NOT NULL, CHANGE dateDeb datedeb VARCHAR(255) NOT NULL, CHANGE dateFin datefin VARCHAR(255) NOT NULL, CHANGE startTime starttime VARCHAR(255) NOT NULL, CHANGE endTime endtime VARCHAR(255) NOT NULL, CHANGE idClub idClub VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE image ADD idProduct VARCHAR(255) NOT NULL, ADD idClub VARCHAR(255) NOT NULL, ADD idEvent VARCHAR(255) NOT NULL, ADD refStadium VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE imageproduct DROP FOREIGN KEY FK_8564BDE6D2F94742');
        $this->addSql('ALTER TABLE imageproduct DROP FOREIGN KEY FK_8564BDE6C3F36F5F');
        $this->addSql('DROP INDEX IDX_8564BDE6D2F94742 ON imageproduct');
        $this->addSql('DROP INDEX IDX_8564BDE6C3F36F5F ON imageproduct');
        $this->addSql('DROP INDEX `PRIMARY` ON imageproduct');
        $this->addSql('ALTER TABLE imageproduct ADD product_id INT NOT NULL, ADD image_id INT NOT NULL, DROP idImage, DROP idProduct');
        $this->addSql('ALTER TABLE imageproduct ADD CONSTRAINT FK_8564BDE63DA5256D FOREIGN KEY (image_id) REFERENCES image (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE imageproduct ADD CONSTRAINT FK_8564BDE64584665A FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE CASCADE');
        $this->addSql('CREATE INDEX IDX_8564BDE64584665A ON imageproduct (product_id)');
        $this->addSql('CREATE INDEX IDX_8564BDE63DA5256D ON imageproduct (image_id)');
        $this->addSql('ALTER TABLE imageproduct ADD PRIMARY KEY (product_id, image_id)');
        $this->addSql('ALTER TABLE notification DROP FOREIGN KEY FK_BF5476CAFE6E88D7');
        $this->addSql('DROP INDEX IDX_BF5476CAFE6E88D7 ON notification');
        $this->addSql('ALTER TABLE notification CHANGE idUser iduser_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_BF5476CA786A81FB FOREIGN KEY (iduser_id) REFERENCES user (id)');
        $this->addSql('CREATE INDEX IDX_BF5476CA786A81FB ON notification (iduser_id)');
        $this->addSql('ALTER TABLE `order` DROP FOREIGN KEY FK_F5299398785ED629');
        $this->addSql('DROP INDEX IDX_F5299398785ED629 ON `order`');
        $this->addSql('ALTER TABLE `order` CHANGE date date VARCHAR(255) NOT NULL, CHANGE idCart idCart VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE payment DROP FOREIGN KEY FK_6D28840DFE6E88D7');
        $this->addSql('DROP INDEX IDX_6D28840DFE6E88D7 ON payment');
        $this->addSql('ALTER TABLE payment ADD idEvent VARCHAR(255) NOT NULL, ADD idOder VARCHAR(255) NOT NULL, ADD idReservation VARCHAR(255) NOT NULL, ADD idSubscription VARCHAR(255) NOT NULL, CHANGE idUser idUser VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE paymentevent DROP FOREIGN KEY FK_4708EDC87D91EFFF');
        $this->addSql('ALTER TABLE paymentevent DROP FOREIGN KEY FK_4708EDC82C6A49BA');
        $this->addSql('DROP INDEX IDX_4708EDC87D91EFFF ON paymentevent');
        $this->addSql('DROP INDEX IDX_4708EDC82C6A49BA ON paymentevent');
        $this->addSql('DROP INDEX `PRIMARY` ON paymentevent');
        $this->addSql('ALTER TABLE paymentevent ADD event_id INT NOT NULL, ADD payment_id INT NOT NULL, DROP idPayment, DROP idEvent');
        $this->addSql('ALTER TABLE paymentevent ADD CONSTRAINT FK_4708EDC84C3A3BB FOREIGN KEY (payment_id) REFERENCES payment (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE paymentevent ADD CONSTRAINT FK_4708EDC871F7E88B FOREIGN KEY (event_id) REFERENCES event (id) ON DELETE CASCADE');
        $this->addSql('CREATE INDEX IDX_4708EDC84C3A3BB ON paymentevent (payment_id)');
        $this->addSql('CREATE INDEX IDX_4708EDC871F7E88B ON paymentevent (event_id)');
        $this->addSql('ALTER TABLE paymentevent ADD PRIMARY KEY (event_id, payment_id)');
        $this->addSql('ALTER TABLE paymentorder DROP FOREIGN KEY FK_898F74F77D91EFFF');
        $this->addSql('ALTER TABLE paymentorder DROP FOREIGN KEY FK_898F74F7E2EDD085');
        $this->addSql('DROP INDEX IDX_898F74F77D91EFFF ON paymentorder');
        $this->addSql('DROP INDEX IDX_898F74F7E2EDD085 ON paymentorder');
        $this->addSql('DROP INDEX `PRIMARY` ON paymentorder');
        $this->addSql('ALTER TABLE paymentorder ADD order_id INT NOT NULL, ADD payment_id INT NOT NULL, DROP idPayment, DROP idOrder');
        $this->addSql('ALTER TABLE paymentorder ADD CONSTRAINT FK_898F74F78D9F6D38 FOREIGN KEY (order_id) REFERENCES `order` (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE paymentorder ADD CONSTRAINT FK_898F74F74C3A3BB FOREIGN KEY (payment_id) REFERENCES payment (id) ON DELETE CASCADE');
        $this->addSql('CREATE INDEX IDX_898F74F78D9F6D38 ON paymentorder (order_id)');
        $this->addSql('CREATE INDEX IDX_898F74F74C3A3BB ON paymentorder (payment_id)');
        $this->addSql('ALTER TABLE paymentorder ADD PRIMARY KEY (order_id, payment_id)');
        $this->addSql('ALTER TABLE paymentreservation DROP FOREIGN KEY FK_147538F87D91EFFF');
        $this->addSql('ALTER TABLE paymentreservation DROP FOREIGN KEY FK_147538F8840939FA');
        $this->addSql('DROP INDEX IDX_147538F87D91EFFF ON paymentreservation');
        $this->addSql('DROP INDEX IDX_147538F8840939FA ON paymentreservation');
        $this->addSql('DROP INDEX `PRIMARY` ON paymentreservation');
        $this->addSql('ALTER TABLE paymentreservation ADD reservation_id INT NOT NULL, ADD payment_id INT NOT NULL, DROP idreservation, DROP idPayment');
        $this->addSql('ALTER TABLE paymentreservation ADD CONSTRAINT FK_147538F84C3A3BB FOREIGN KEY (payment_id) REFERENCES payment (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE paymentreservation ADD CONSTRAINT FK_147538F8B83297E7 FOREIGN KEY (reservation_id) REFERENCES reservation (id) ON DELETE CASCADE');
        $this->addSql('CREATE INDEX IDX_147538F8B83297E7 ON paymentreservation (reservation_id)');
        $this->addSql('CREATE INDEX IDX_147538F84C3A3BB ON paymentreservation (payment_id)');
        $this->addSql('ALTER TABLE paymentreservation ADD PRIMARY KEY (reservation_id, payment_id)');
        $this->addSql('ALTER TABLE paymentsubscription DROP FOREIGN KEY FK_BF706F77D91EFFF');
        $this->addSql('ALTER TABLE paymentsubscription DROP FOREIGN KEY FK_BF706F7FD58C022');
        $this->addSql('DROP INDEX IDX_BF706F77D91EFFF ON paymentsubscription');
        $this->addSql('DROP INDEX IDX_BF706F7FD58C022 ON paymentsubscription');
        $this->addSql('DROP INDEX `PRIMARY` ON paymentsubscription');
        $this->addSql('ALTER TABLE paymentsubscription ADD subscription_id INT NOT NULL, ADD payment_id INT NOT NULL, DROP idPayment, DROP idSubscription');
        $this->addSql('ALTER TABLE paymentsubscription ADD CONSTRAINT FK_BF706F74C3A3BB FOREIGN KEY (payment_id) REFERENCES payment (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE paymentsubscription ADD CONSTRAINT FK_BF706F79A1887DC FOREIGN KEY (subscription_id) REFERENCES subscription (id) ON DELETE CASCADE');
        $this->addSql('CREATE INDEX IDX_BF706F79A1887DC ON paymentsubscription (subscription_id)');
        $this->addSql('CREATE INDEX IDX_BF706F74C3A3BB ON paymentsubscription (payment_id)');
        $this->addSql('ALTER TABLE paymentsubscription ADD PRIMARY KEY (subscription_id, payment_id)');
        $this->addSql('ALTER TABLE reservation DROP FOREIGN KEY FK_42C84955FB08D2FF');
        $this->addSql('DROP INDEX IDX_42C84955FB08D2FF ON reservation');
        $this->addSql('ALTER TABLE reservation DROP FOREIGN KEY FK_42C84955A593B2A9');
        $this->addSql('ALTER TABLE reservation CHANGE date date VARCHAR(255) NOT NULL, CHANGE startTime starttime VARCHAR(255) NOT NULL, CHANGE endTime endtime VARCHAR(255) NOT NULL, CHANGE idPlayer idPlayer VARCHAR(255) NOT NULL');
        $this->addSql('DROP INDEX idx_42c84955a593b2a9 ON reservation');
        $this->addSql('CREATE INDEX IDX_42C849556A2E8B35 ON reservation (refstadium)');
        $this->addSql('ALTER TABLE reservation ADD CONSTRAINT FK_42C84955A593B2A9 FOREIGN KEY (refStadium) REFERENCES stadium (reference)');
        $this->addSql('ALTER TABLE stadium DROP FOREIGN KEY FK_E604044FCB1366EC');
        $this->addSql('DROP INDEX IDX_E604044FCB1366EC ON stadium');
        $this->addSql('ALTER TABLE stadium CHANGE idClub idclub_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE stadium ADD CONSTRAINT FK_E604044FBE1D585C FOREIGN KEY (idclub_id) REFERENCES club (id)');
        $this->addSql('CREATE INDEX IDX_E604044FBE1D585C ON stadium (idclub_id)');
        $this->addSql('ALTER TABLE subscription DROP FOREIGN KEY FK_A3C664D33E12C423');
        $this->addSql('ALTER TABLE subscription DROP FOREIGN KEY FK_A3C664D3FE6E88D7');
        $this->addSql('DROP INDEX IDX_A3C664D33E12C423 ON subscription');
        $this->addSql('DROP INDEX IDX_A3C664D3FE6E88D7 ON subscription');
        $this->addSql('ALTER TABLE subscription CHANGE startDate startdate VARCHAR(255) NOT NULL, CHANGE endDate enddate VARCHAR(255) NOT NULL, CHANGE idOffer idOffer VARCHAR(255) NOT NULL, CHANGE idUser iduser_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE subscription ADD CONSTRAINT FK_A3C664D3786A81FB FOREIGN KEY (iduser_id) REFERENCES user (id)');
        $this->addSql('CREATE INDEX IDX_A3C664D3786A81FB ON subscription (iduser_id)');
        $this->addSql('ALTER TABLE user ADD idEvent VARCHAR(255) NOT NULL, DROP is_verified, CHANGE firstName firstname VARCHAR(255) NOT NULL, CHANGE lastName lastname VARCHAR(255) NOT NULL, CHANGE birthDate birthdate VARCHAR(255) NOT NULL, CHANGE email email VARCHAR(255) NOT NULL, CHANGE creationDate creationdate VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE useractivitylog DROP FOREIGN KEY FK_AC92FBF7FE6E88D7');
        $this->addSql('DROP INDEX IDX_AC92FBF7FE6E88D7 ON useractivitylog');
        $this->addSql('ALTER TABLE useractivitylog ADD logintimestamp VARCHAR(255) NOT NULL, DROP loginTime, CHANGE idUser userid_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE useractivitylog ADD CONSTRAINT FK_AC92FBF758E0A285 FOREIGN KEY (userid_id) REFERENCES user (id)');
        $this->addSql('CREATE INDEX IDX_AC92FBF758E0A285 ON useractivitylog (userid_id)');
    }
}
